#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  ./make-valid-gpg-key.sh [options] <input-key> <real-name> <email> [output-key]

Arguments:
  <input-key>  Secret key file generated by gpg-fingerprint-filter-gpu
  <real-name>  User name to add to the key
  <email>      Email address to add to the key
  [output-key] Output path for the updated secret key

Options:
  --add-encryption-subkey
      Add a new random cv25519 encryption subkey before export
  --add-existing-encryption-subkey <key-file>
      Add an existing generated cv25519 key as an encryption subkey,
      preserving its fingerprint by reusing its embedded creation time

If [output-key] is omitted, the script writes:
  <input-key basename>.valid.gpg

The script works in a temporary GNUPGHOME so it does not modify your main keyring.
EOF
}

add_encryption_subkey=0
existing_encryption_subkey=

while [[ $# -gt 0 ]]; do
    case "$1" in
        --add-encryption-subkey)
            add_encryption_subkey=1
            shift
            ;;
        --add-existing-encryption-subkey)
            if [[ $# -lt 2 ]]; then
                echo "Missing value for option: $1" >&2
                usage >&2
                exit 1
            fi
            existing_encryption_subkey=$2
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        --*)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

if [[ $# -lt 3 || $# -gt 4 ]]; then
    usage >&2
    exit 1
fi

if [[ "$add_encryption_subkey" -eq 1 && -n "$existing_encryption_subkey" ]]; then
    echo "Use only one of --add-encryption-subkey or --add-existing-encryption-subkey" >&2
    exit 1
fi

input_key=$1
real_name=$2
email=$3
output_key=${4:-}

if [[ ! -f "$input_key" ]]; then
    echo "Input key not found: $input_key" >&2
    exit 1
fi

if [[ -n "$existing_encryption_subkey" && ! -f "$existing_encryption_subkey" ]]; then
    echo "Existing encryption subkey not found: $existing_encryption_subkey" >&2
    exit 1
fi

if [[ -z "$output_key" ]]; then
    input_dir=$(dirname -- "$input_key")
    input_base=$(basename -- "$input_key")
    input_stem=${input_base%.*}
    output_key="$input_dir/$input_stem.valid.gpg"
fi

uid_string="$real_name <$email>"
tmp_gnupg=$(mktemp -d)
chmod 700 "$tmp_gnupg"

cleanup() {
    rm -rf "$tmp_gnupg"
}
trap cleanup EXIT

GNUPGHOME="$tmp_gnupg" gpg --batch --allow-non-selfsigned-uid --import "$input_key" >/dev/null 2>&1

fingerprint=$(
    GNUPGHOME="$tmp_gnupg" gpg --with-colons --list-secret-keys \
    | awk -F: '$1 == "fpr" { print $10; exit }'
)

if [[ -z "$fingerprint" ]]; then
    echo "Failed to read imported key fingerprint" >&2
    exit 1
fi

GNUPGHOME="$tmp_gnupg" gpg --batch --yes --quick-add-uid "$fingerprint" "$uid_string" >/dev/null 2>&1
GNUPGHOME="$tmp_gnupg" gpg --batch --yes --quick-set-primary-uid "$fingerprint" "$uid_string" >/dev/null 2>&1

noname_uid_index=$(
    GNUPGHOME="$tmp_gnupg" gpg --with-colons --list-keys "$fingerprint" \
    | awk -F: '$1 == "uid" { idx += 1; if ($10 == "NONAME") { print idx; exit } }'
)

if [[ -n "$noname_uid_index" ]]; then
    printf 'uid %s\ndeluid\ny\nsave\n' "$noname_uid_index" \
        | GNUPGHOME="$tmp_gnupg" gpg --batch --yes --command-fd 0 --edit-key "$fingerprint" >/dev/null 2>&1
fi

if [[ "$add_encryption_subkey" -eq 1 ]]; then
    GNUPGHOME="$tmp_gnupg" gpg --batch --yes --pinentry-mode loopback --passphrase '' \
        --quick-add-key "$fingerprint" cv25519 encr 0 >/dev/null 2>&1
fi

if [[ -n "$existing_encryption_subkey" ]]; then
    subkey_info=$(
        GNUPGHOME="$tmp_gnupg" gpg --batch --show-keys --with-colons --with-keygrip "$existing_encryption_subkey" \
        | awk -F: '
            ($1 == "pub" || $1 == "sec") && created == "" {
                created = $6
                next
            }
            $1 == "fpr" && fpr == "" {
                fpr = $10
                next
            }
            $1 == "grp" && keygrip == "" {
                keygrip = $10
                next
            }
            END {
                if (created != "" && fpr != "" && keygrip != "") {
                    print created ":" fpr ":" keygrip
                }
            }
        '
    )

    if [[ -z "$subkey_info" ]]; then
        echo "Failed to read existing encryption subkey metadata" >&2
        exit 1
    fi

    IFS=: read -r existing_subkey_created existing_subkey_fingerprint existing_subkey_keygrip <<<"$subkey_info"

    if [[ "$existing_subkey_fingerprint" == "$fingerprint" ]]; then
        echo "Existing encryption subkey must be different from the primary key" >&2
        exit 1
    fi

    GNUPGHOME="$tmp_gnupg" gpg --batch --allow-non-selfsigned-uid --import "$existing_encryption_subkey" >/dev/null 2>&1

    printf 'addkey\n13\n%s\ns\na\nq\n0\ny\nsave\n' "$existing_subkey_keygrip" \
        | GNUPGHOME="$tmp_gnupg" gpg --batch --yes --no-tty --expert \
            --faked-system-time="${existing_subkey_created}!" \
            --ignore-time-conflict \
            --pinentry-mode loopback --passphrase '' \
            --command-fd 0 --edit-key "$fingerprint" >/dev/null 2>&1
fi

GNUPGHOME="$tmp_gnupg" gpg --batch --yes --output "$output_key" --export-secret-keys "$fingerprint"

echo "Fingerprint: $fingerprint"
echo "UID: $uid_string"
if [[ "$add_encryption_subkey" -eq 1 ]]; then
    echo "Added encryption subkey: cv25519 [E]"
fi
if [[ -n "$existing_encryption_subkey" ]]; then
    echo "Added existing encryption subkey: $existing_subkey_fingerprint"
    echo "Existing encryption subkey creation time: $existing_subkey_created"
fi
echo "Wrote valid secret key to: $output_key"
echo "-- with-colons --"
GNUPGHOME="$tmp_gnupg" gpg --with-colons --list-secret-keys "$fingerprint"
echo "-- human --"
GNUPGHOME="$tmp_gnupg" gpg --list-secret-keys --with-keygrip "$fingerprint"
