#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  ./make-valid-gpg-key.sh <input-key> <real-name> <email> [output-key]

Arguments:
  <input-key>  Secret key file generated by gpg-fingerprint-filter-gpu
  <real-name>  User name to add to the key
  <email>      Email address to add to the key
  [output-key] Output path for the updated secret key

If [output-key] is omitted, the script writes:
  <input-key basename>.valid.gpg

The script works in a temporary GNUPGHOME so it does not modify your main keyring.
EOF
}

if [[ $# -lt 3 || $# -gt 4 ]]; then
    usage >&2
    exit 1
fi

input_key=$1
real_name=$2
email=$3
output_key=${4:-}

if [[ ! -f "$input_key" ]]; then
    echo "Input key not found: $input_key" >&2
    exit 1
fi

if [[ -z "$output_key" ]]; then
    input_dir=$(dirname -- "$input_key")
    input_base=$(basename -- "$input_key")
    input_stem=${input_base%.*}
    output_key="$input_dir/$input_stem.valid.gpg"
fi

uid_string="$real_name <$email>"
tmp_gnupg=$(mktemp -d)
chmod 700 "$tmp_gnupg"

cleanup() {
    rm -rf "$tmp_gnupg"
}
trap cleanup EXIT

GNUPGHOME="$tmp_gnupg" gpg --batch --allow-non-selfsigned-uid --import "$input_key" >/dev/null 2>&1

fingerprint=$(
    GNUPGHOME="$tmp_gnupg" gpg --with-colons --list-secret-keys \
    | awk -F: '$1 == "fpr" { print $10; exit }'
)

if [[ -z "$fingerprint" ]]; then
    echo "Failed to read imported key fingerprint" >&2
    exit 1
fi

GNUPGHOME="$tmp_gnupg" gpg --batch --yes --quick-add-uid "$fingerprint" "$uid_string" >/dev/null 2>&1
GNUPGHOME="$tmp_gnupg" gpg --batch --yes --quick-set-primary-uid "$fingerprint" "$uid_string" >/dev/null 2>&1

noname_uid_index=$(
    GNUPGHOME="$tmp_gnupg" gpg --with-colons --list-keys "$fingerprint" \
    | awk -F: '$1 == "uid" { idx += 1; if ($10 == "NONAME") { print idx; exit } }'
)

if [[ -n "$noname_uid_index" ]]; then
    printf 'uid %s\ndeluid\ny\nsave\n' "$noname_uid_index" \
        | GNUPGHOME="$tmp_gnupg" gpg --batch --yes --command-fd 0 --edit-key "$fingerprint" >/dev/null 2>&1
fi

GNUPGHOME="$tmp_gnupg" gpg --batch --yes --output "$output_key" --export-secret-keys "$fingerprint"

echo "Fingerprint: $fingerprint"
echo "UID: $uid_string"
echo "Wrote valid secret key to: $output_key"
